FROM python:3.13.5-bookworm
RUN useradd --create-home lada
WORKDIR /home/lada
ENV PIP_ROOT_USER_ACTION=ignore
RUN pip install --no-deps --no-cache-dir --requirement https://raw.githubusercontent.com/ladaapp/lada/refs/heads/main/packaging/requirements-cli.txt
RUN pip install --no-deps --no-cache-dir 'lada[basicvsrpp]@git+https://github.com/ladaapp/lada.git'
RUN curl -Ls https://raw.githubusercontent.com/ladaapp/lada/refs/heads/main/patches/increase_mms_time_limit.patch | patch -u -p2 -d /usr/local
RUN curl -Ls https://raw.githubusercontent.com/ladaapp/lada/refs/heads/main/patches/remove_ultralytics_telemetry.patch | patch -u -p2 -d /usr/local
RUN curl -Ls https://raw.githubusercontent.com/ladaapp/lada/refs/heads/main/patches/fix_loading_mmengine_weights_on_torch26_and_higher.diff | patch -u -p2 -d /usr/local
RUN mkdir ffmpeg && curl -L 'https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz' | tar xJf - -C ffmpeg  --strip-components 2 ffmpeg-master-latest-linux64-gpl/bin/ffprobe ffmpeg-master-latest-linux64-gpl/bin/ffmpeg && chmod -R 555 ffmpeg
ENV PATH="/home/lada/ffmpeg:$PATH"
RUN mkdir -p /home/lada/.config/Ultralytics \
    && echo '{"settings_version":"0.0.6","datasets_dir":"datasets","weights_dir":"weights","runs_dir":"experiments","uuid":"dummy","sync":false,"api_key":"","openai_api_key":"","clearml":false,"comet":false,"dvc":false,"hub":false,"mlflow":false,"neptune":false,"raytune":false,"tensorboard":false,"wandb":false,"vscode_msg":false,"openvino_msg":false}' > /home/lada/.config/Ultralytics/settings.json \
    && chown -R lada:lada /home/lada/.config
RUN mkdir -p model_weights/3rd_party mnt && chmod -R 555 model_weights && chmod 777 mnt
ADD --checksum=sha256:5707c3af78a13ef8d60d0c3a3ea420e79745ac5c9b7d792e3a13598fcdedfc8f \
    https://github.com/ladaapp/lada/releases/download/v0.7.0/lada_mosaic_detection_model_v3.pt model_weights/lada_mosaic_detection_model_v3.pt
ADD --checksum=sha256:d404152576ce64fb5b2f315c03062709dac4f5f8548934866cd01c823c8104ee \
    https://github.com/ladaapp/lada/releases/download/v0.6.0/lada_mosaic_restoration_model_generic_v1.2.pth model_weights/lada_mosaic_restoration_model_generic_v1.2.pth
ADD --checksum=sha256:5643ca297c13920b8ffd39a0d85296e494683a69e5e8204d662653d24c582766 \
    https://drive.usercontent.google.com/download?id=1ulct4RhRxQp1v5xwEmUH7xz7AK42Oqlw&export=download&confirm=t model_weights/3rd_party/clean_youknow_video.pth
RUN chmod 444 model_weights/*\.pt* model_weights/3rd_party/*\.pt*
USER lada

ENTRYPOINT ["lada-cli"]
CMD ["--help"]